from fastapi import FastAPI, UploadFile, File
from fastapi.responses import FileResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
import os
import gdown
import textwrap
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from ai_dl.check import Check_Tumor
from ai_dl.ai_agent import Agentic_ai

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


model = Check_Tumor()


def detect_tumor(file_path: str):
    sentence = model.check(file_path)
    return sentence


def agent_ai(file_path: str, type_img: str):
    class_ = Agentic_ai()
    report_text = class_.main(file_path, type_img)
    return report_text




def generate_pdf(report_text: str, type_img: str, image_path: str):

    os.makedirs("pdfs", exist_ok=True)

    pdf_file_name = "pdfs/brain_tumor_detection.pdf"

    c = canvas.Canvas(pdf_file_name, pagesize=letter)

    c.setFont("Helvetica-Bold", 18)
    c.drawString(150, 750, "BRAIN TUMOR DETECTION REPORT")

    c.setFont("Helvetica", 12)
    c.drawString(50, 730, f"Detected Type: {type_img}")

    y = 700

    lines = report_text.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            continue

        if len(line) > 1 and line[0].isdigit() and line[1] == ".":

            wrapped = textwrap.wrap(line, width=80)

            for i, wline in enumerate(wrapped):

                if i == 0:
                    c.drawString(50, y, wline)
                else:
                    c.drawString(70, y, wline)

                y -= 18

                if y < 120:
                    c.showPage()
                    c.setFont("Helvetica", 12)
                    y = 750

        else:

            wrapped = textwrap.wrap(line, width=80)

            for wline in wrapped:
                c.drawString(70, y, wline)
                y -= 18

                if y < 120:
                    c.showPage()
                    c.setFont("Helvetica", 12)
                    y = 750

    # New page for MRI image
    c.showPage()

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 750, "MRI Scan Image")

    try:
        c.drawImage(image_path, 150, 400, width=300, height=250)
    except:
        pass

    c.setFont("Helvetica", 10)
    c.drawString(50, 40, "Generated By AI Diagnostic System")

    c.save()

    return pdf_file_name



@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    try:

        uploads = "image_uploaded"
        MODEL_PATH = "brain_tumor_detection_improved.h5"
        os.makedirs(uploads, exist_ok=True)
        url = "https://drive.google.com/uc?id=1RGbvYsIEZrZYQXo6XXwjWFADGq5cm--9"    
        gdown.download(url,MODEL_PATH,quiet=False)
        file_name = file.filename
        file_path = os.path.join(uploads, file_name)

        contents = await file.read()

        with open(file_path, "wb") as f:
            f.write(contents)

        type_img = detect_tumor(file_path)

        report_text = agent_ai(file_path, type_img)

        pdf = generate_pdf(report_text, type_img, file_path)

        return FileResponse(
            pdf,
            media_type="application/pdf",
            filename="Brain Tumor Report.pdf"
        )

    except Exception as e:

        return JSONResponse(
            status_code=500,
            content={"message": "Prediction failed"}
        )


app.mount("/assets", StaticFiles(directory="dist/assets"), name="assets")


@app.get("/")
def serve_react():
    return FileResponse("dist/index.html")

@app.get("/{path:path}")
async def catch_all(path: str):
    return FileResponse("dist/index.html")